---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: English
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*.cn.md"
  new_doc_ext: cn.md
- type: heading
  label: Simplified Chinese
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*.en.md"
  new_doc_ext: en.md
- type: heading
  label: Documentation
- type: heading
  label: Feedback
upload_dir: neuron/media
public_path: https://res.cloudinary.com/jmao/neuron/media
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
